# Generated by Django 5.1.3 on 2024-11-23 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.CharField(max_length=200)),
                ('localizacao', models.CharField(max_length=200)),
                ('imagem', models.CharField(default='', max_length=200)),
                ('tipo', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=200)),
                ('pdf', models.FileField(blank=True, null=True, upload_to='pdfs/')),
                ('likes', models.IntegerField()),
                ('deslikes', models.IntegerField()),
                ('comentarios', models.CharField(max_length=500)),
                ('contratante', models.CharField(max_length=200)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.users')),
            ],
        ),
    ]
