# Generated by Django 5.1.3 on 2024-11-24 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratantes', '0001_initial'),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='comentarios',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='contratante',
        ),
        migrations.AddField(
            model_name='posts',
            name='contratantes',
            field=models.ManyToManyField(related_name='posts', to='contratantes.contratantes'),
        ),
    ]
