# Generated by Django 5.1.3 on 2024-11-23 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('senha', models.CharField(max_length=200)),
                ('papel', models.CharField(default='cidadao', max_length=200)),
                ('pontos', models.FloatField(default=0.0)),
                ('nivel', models.IntegerField(default=1)),
            ],
        ),
    ]
