# Generated by Django 5.1.4 on 2024-12-08 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='bairro',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='rua',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
