# Generated by Django 5.1.3 on 2024-12-04 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_users_senha_users_last_login_users_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='users',
            name='password',
        ),
        migrations.AddField(
            model_name='users',
            name='senha',
            field=models.CharField(default='password123', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='users',
            name='papel',
            field=models.CharField(default='cidadao', max_length=200),
        ),
    ]
