# Generated by Django 5.1.3 on 2024-11-24 03:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentarios',
            name='autor',
        ),
        migrations.AddField(
            model_name='comentarios',
            name='deslikes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='comentarios',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='comentarios',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.users'),
            preserve_default=False,
        ),
    ]
