# Generated by Django 5.1.4 on 2024-12-05 05:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('mensagem', models.TextField()),
                ('bairros', models.TextField(blank=True, null=True)),
                ('todos_usuarios', models.BooleanField(default=False)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('usuarios', models.ManyToManyField(blank=True, related_name='notificacoes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
