# Generated by Django 5.1.3 on 2024-11-30 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('mensagem', models.TextField()),
                ('bairros', models.TextField(blank=True, null=True)),
                ('todos_usuarios', models.BooleanField(default=False)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('usuarios', models.ManyToManyField(blank=True, related_name='notificacoes', to='users.users')),
            ],
        ),
    ]
